    def visitFor(self,ctx,o):
        code,typ = self.visit(ctx.ini,Access(o.frame,o.sym,False))
        self.emit.printout(code)
        code,typ = self.visit(ctx.idx,Access(o.frame,o.sym,True))
        self.emit.printout(code)
        loopLabel=o.frame.getNewLabel()
        o.frame.enterLoop()
        cont = o.frame.getContinueLabel()
        brk = o.frame.getBreakLabel()
        self.emit.printout(self.emit.emitLABEL(loopLabel,o.frame))
        code,typ = self.visit(ctx.idx,Access(o.frame,o.sym,False))
        self.emit.printout(code)
        code,typ=self.visit(ctx.end,Access(o.frame,o.sym,False))
        self.emit.printout(code)
        self.emit.printout(self.emit.emitREOP('<=',IntType(),o.frame))
        self.emit.printout(self.emit.emitIFFALSE(brk,o.frame))
        self.visit(ctx.stmt,o)
        self.emit.printout(self.emit.emitLABEL(cont,o.frame))
        code,typ=self.visit(ctx.upd,Access(o.frame,o.sym,False))
        self.emit.printout(code)
        code,typ=self.visit(ctx.idx,Access(o.frame,o.sym,False))
        self.emit.printout(code)
        self.emit.printout(self.emit.emitADDOP('+',IntType(),o.frame))
        code,typ = self.visit(ctx.idx,Access(o.frame,o.sym,True))
        self.emit.printout(code)
        self.emit.printout(self.emit.emitGOTO(loopLabel,o.frame))
        self.emit.printout(self.emit.emitLABEL(brk,o.frame))
        o.frame.exitLoop()
        